src/routes/main.py
from flask import Blueprint, render_template, request
from flask_login import current_user, login_required

from forms import usuario

main = Blueprint("main", __name__)


@main.route("/")
def index():
    return render_template("index.html")


@main.route("/inicio")
@login_required
def menu():
    usuario = current_user.nombre
    admin = current_user.has_role("admin")
    vendedor = current_user.has_role("vendedor")
    cocinero = current_user.has_role("cocinero")
    mensaje = f"Bienvenido {usuario} "
    if admin or vendedor or cocinero:
        mensaje += " tienes "
        if admin and vendedor and cocinero:
            mensaje += "todos los permisos del sistema."
        if admin and vendedor and not cocinero:
            mensaje += "permisos de administrador y vendedor."
        if admin and cocinero and not vendedor:
            mensaje += "permisos de administrador y cocinero."
        if vendedor and cocinero and not admin:
            mensaje += "permisos de vendedor y cocinero."
        if admin and not vendedor and not cocinero:
            mensaje += "permisos de administrador."
        if vendedor and not admin and not cocinero:
            mensaje += "permisos de vendedor."
        if cocinero and not admin and not vendedor:
            mensaje += "permisos de cocinero."
    else:
        mensaje += "no tienes rol asignado."

    return render_template("inicio.html", mensaje=mensaje)


@main.route("/configuracion")
@login_required
def configuracion():
    """Ruta para la configuración del usuario"""

    form_usuario = usuario.UsuarioForm(request.form)
    return render_template("configuracion/configuracion.html", formUsuario=form_usuario)

src/templates/_macros.html
{%macro render_field(field)%}
  <td>{{field.label}}</td>
  {{field(**kwargs) | safe}} 

  {%if field.errors%}
  <ul class="errors">
    {%for error in field.errors%}
    <li style="color: red">{{error}}</li>
    {%endfor%}
  </ul>
  {%endif%} 

{%endmacro%} 

{%macro render_field_nolabel(field)%} 
  
  {{field(**kwargs) | safe}} 

  {%if field.errors%}
  <ul class="errors">
    {%for error in field.errors%}
    <li style="color: red">{{error}}</li>
    {%endfor%}
  </ul>
  {%endif%} 

{%endmacro%} 

{%macro datos(name, placeholder, type='text')%}
<p><input name="{{name}}" placeholder="{{placeholder}}" type="{{type}}" /></p>
{%endmacro%} 

{% macro input_float(field) %}
<div class="form-floating mb-3 mt-3 mx-5">
  <input 
         type="{{ get_field_type(field) }}" 
        class="form-control {{ 'is-invalid' if field.errors else '' }}" 
        id="{{ field.name }}" 
        name="{{ field.name }}" 
        placeholder="{{ field.label.text }}"
        {% if field.data %}
            value="{{ field.data }}"
        {% endif %}
        
    >
  <label id="lb_{{ field.name }}" for="{{ field.name }}">
        {{field.label.text}}
    </label>    

</div>

  {% if field.errors %}
    <ul class="errors">
        {% for error in field.errors %}
        <li style="color: red;">
            {{ error }}
        </li>
        {% endfor %}
    </ul>
  {% endif %}

{% endmacro %}

{% macro input(field) %}
<div class="mb-3 mt-3 mx-5">
  <input 
        type="{{ field.type }}" 
        class="form-control  {{ 'is-invalid' if field.errors else '' }}" 
        id="{{ field.name }}" 
        name="{{ field.name }}" 
        placeholder="{{ field.label.text }}"
        {% if field.data %}
            value="{{ field.data }}"
        {% endif %}
        
    >
</div>

  {% if field.errors %}
    <ul class="errors">
        {% for error in field.errors %}
        <li style="color: red;">
            {{ error }}
        </li>
        {% endfor %}
    </ul>
  {% endif %}

{% endmacro %}

{% macro date_field(field) %}
<div class="mb-3 mt-3">
  <label for="{{field.id}}">{{field.label}}</label>
  {{field(**kwargs)|safe}} {% if field.errors %}
  <ul>
    {% for error in field.errors %}
    <li style="color: red">{{ error }}</li>
    {% endfor %}
  </ul>

  {% endif %}
</div>
{% endmacro %} 

{% macro radio_list(field) %} 

  {% for option in field %}
    <div class="form-check">
      <label class="form-check-label" for="{{ option.id }}">
        {{option.label.text|safe}}
      </label>
      {{option(**kwargs)|safe}}
    </div>
  {% endfor %} 

{% endmacro %} 

{% macro check_box(field) %}

  <div class="form-check">
    {{field(**kwargs)|safe}}
    <label class="form-check-label text-uppercase" for="{{ field.id }}">
      {{field.label}}
    </label>
  </div>

{% endmacro %}


{% macro select(field, option_selected) %}
<div class="form-floating mb-3 mt-3 mx-5">
    <select 
        type="{{ field.type }}" 
        class="form-select {{ 'is-invalid' if field.errors else '' }}" 
        id="{{ field.name }}" 
        name="{{ field.name }}" 
        
    >
        <option value="">Selecciona una opción</option>
        {% for choice in field.choices %}
  
        <option value="{{ choice[0] }}" {% if choice[0]|string == option_selected|string %} selected {% endif %}>
            {{ choice[1] }}
        </option>
        {% endfor %}
    </select>
    <label for="{{ field.name}}">
        {{field.label.text}}
    </label>
    

  {% if field.errors %}
  <ul>
    {% for error in field.errors %}
    <li style="color: red">{{ error }}</li>
    {% endfor %}
  </ul>

  {% endif %}
</div>
{% endmacro %}

{% macro submit_button(button) %}
<div class="text-center">
    <button type="{{ button.type }}" class="btn btn-primary">
        {{ button.label.text }}
    </button>
</div>
{% endmacro %}

src/templates/error_page.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>error</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/404.css')}}"
    />
    <link
      rel="icon"
      type="image/png"
      href="{{ url_for('static', filename='img/cookie_1.png')}}"
    />
  </head>

  <body>
    <div class="hero-bg">
      <div class="particles-container">
        <canvas id="hero-particles"></canvas>
      </div>
    </div>

    <div class="error-container">
      <div class="cookie">
        <img
          src="{{ url_for('static', filename='img/cookie_19.png')}}"
          alt="Logo de la empresa"
          class="que busca compa"
        />
      </div>
      <div class="error">
        <div class="error__title">
          <div class="words">
            <span>{{ error[0] }}</span>
            <span>{{ error[1] }}</span>
            <span>{{ error[2] }}</span>
          </div>
        </div>
        <div class="error__subtitle">Hmmm...</div>
        <div class="error__description">{{ mensaje }}</div>
        <div class="button-group">
          <div class="button">
            <a href="{{ url_for('auth.login' )}}"> Si </a>
          </div>
        </div>
      </div>
    </div>

    <script src="https://unpkg.com/scrollreveal@4.0.5/dist/scrollreveal.min.js"></script>
    <script src="{{ url_for('static', filename='js/404.js')}}"></script>
  </body>
</html>

src/templates/index.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>CooKing - El Rey de las Galletas</title>
    <link
      href="https://fonts.googleapis.com/css?family=Heebo:400,700|Oxygen:700"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="../static/css/index_decorator.css" />
    <link rel="icon" type="image/png" href="../static/img/cookie_1.png" />
    <link rel="stylesheet" href="../static/css/bootstrap.min.css">
    
    <script src="https://unpkg.com/scrollreveal@4.0.5/dist/scrollreveal.min.js"></script>
    <script src="../static/js/bootstrap.min.js"></script>
  </head>
  <body class="is-boxed has-animations">
    <div class="body-wrap">
      <main>
        <section class="hero text-center text-light">
          <div class="hero-bg">
            <div class="particles-container">
              <canvas id="hero-particles"></canvas>
            </div>
          </div>
          <div class="container-sm">
            <div class="hero-inner">
              <div class="hero-copy">
                <div class="words">
                  <span>C</span>
                  <span>O</span>
                  <span>O</span>
                  <span>K</span>
                  <span>I</span>
                  <span>N</span>
                  <span>G</span>
                </div>
                <div class="button">
                  <a href="{{ url_for('auth.login' )}}"> INGRESAR </a>
                </div>
              </div>
              <div class="mockup-container">
                <img
                  class="device-mockup"
                  src="../static/img/cooking_1.png"
                  alt="Galleta de CooKing"
                />
              </div>
            </div>
          </div>
        </section>

        <section class="features-extended section">
          <div class="features-extended-inner section-inner">
            <div class="features-extended-wrap">
              <div class="container">
                <div class="feature-extended">
                  <div class="feature-extended-image">
                    <div class="mockup-bg">
                      <img
                        src="../static/img/index_decorator/fondo1.svg"
                        alt="Ilustración de iPhone"
                      />
                    </div>
                    <img
                      class="device-mockup is-revealing"
                      src="../static/img/index_decorator/arco_calzada.png"
                      alt="Galleta de CooKing"
                    />
                  </div>
                  <div class="feature-extended-body is-revealing">
                    <h3 class="mt-0 mb-16">
                      El orgullo de León en cada galleta
                    </h3>
                    <p class="m-0">
                      CooKing es más que una tienda de galletas, es un sistema
                      de gestión que te permite llevar el control de la
                      producción y venta de tus galletas artesanales con
                      facilidad.
                    </p>
                  </div>
                </div>
                <div class="feature-extended">
                  <div class="feature-extended-image">
                    <div class="mockup-bg">
                      <img
                        src="../static/img/index_decorator/fondo0.svg"
                        alt="Ilustración de iPhone"
                      />
                    </div>
                    <img
                      class="device-mockup is-revealing feature-image"
                      src="../static/img/cookie_17.png"
                      alt="Galleta de CooKing"
                    />
                  </div>
                  <div class="feature-extended-body is-revealing">
                    <h3 class="mt-0 mb-16">
                      Innovación y calidad en cada paso
                    </h3>
                    <p class="m-0">
                      Con CooKing, cada paso de la producción de tus galletas
                      artesanales está optimizado para garantizar la mejor
                      calidad y sabor. Nuestro sistema te permite innovar y
                      crecer.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>

      <footer class="site-footer">
        <div class="particles-container">
          <canvas id="footer-particles"></canvas>
        </div>
        <div class="site-footer-top">
          <section class="cta section text-light">
            <div class="container-sm">
              <div class="cta-inner section-inner">
                <div class="cta-header text-center">
                  <h2 class="section-title mt-0">
                    Únete a la revolución de las galletas
                  </h2>
                  <p class="section-paragraph">
                    Descubre cómo CooKing puede transformar tu negocio de
                    galletas artesanales y llevarlo al siguiente nivel.
                  </p>
                  <div class="cta-cta">
                    <a class="" href="{{ url_for('auth.login') }}"
                      >
                      <button class="btn btn-outline-primary">Accede al sistema</button></a
                    >
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
        <div class="site-footer-bottom">
          <div class="container">
            <div class="site-footer-inner">
              <div class="brand footer-brand">
                <a href="#">
                  <img
                    src="../static/img/logo.png"
                    style="height: 80px"
                    alt="Logo de CooKing"
                  />
                </a>
              </div>
              <ul class="footer-links list-reset">
                <li>
                  <a href="#">Contacto</a>
                </li>
                <li>
                  <a href="#">Sobre nosotros</a>
                </li>
                <li>
                  <a href="#">Preguntas frecuentes</a>
                </li>
                <li>
                  <a href="#">Soporte</a>
                </li>
              </ul>
              <ul class="footer-social-links list-reset">
                <!-- Aquí puedes agregar los enlaces a las redes sociales -->
              </ul>
              <div class="footer-copyright">
                &copy; 2024 CooKing, todos los derechos reservados
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>

    <script src="../static/js/index_decorator.js"></script>
  </body>
</html>

src/templates/inicio.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>CooKing - {% block title %}{% endblock %}</title>

  {% include 'librerias/librerias.html' %}

  {% block styles %}
  {% endblock %}
</head>

<body>
  <div class="Menu">
    <div class="logo-container">
      <a href="{{url_for('main.menu')}}"><img src="{{ url_for('static', filename='img/logo.png')}}"
          alt="Logo de la empresa" class="company-logo" /></a>
    </div>

    {% include 'sidebar/sidebar.html' %}

    <div class="Content">
      {% block content %}
      <div style="
            display: flex;
            height: 100%;
            width: 100%;
            align-items: center;
            justify-content: center;
            background-image: url(../static/img/cookie_17.png);
            background-size: cover;
            overflow: hidden;
          ">
        <h1 style="
              padding: 150px 200px;
              margin: 0 50px;
              background: #00000095;
              border-radius: 20px;
              font-weight: 900;
              font-size: 5rem;
              text-align: center;
              color: #ffe8bd;
            ">
          Bievenido a CooKing
        </h1>
      </div>

      <script>
        localStorage.setItem("mensaje", "{{mensaje}}");
      </script>

      <script src="{{ url_for('static', filename='js/menu.js')}}"></script>
      <script>
        Toast.fire({
          icon: "success",
          title: localStorage.getItem("mensaje"),
        });
      </script>
      {% endblock %}
    </div>
  </div>

  {% block bootstrap_modals %}{% endblock %}
  <script src="{{ url_for('static', filename='js/sidebar.js')}}"></script>

  <!-- BLOQUE PARA CODIGO -->
  {% block jscode %} {% endblock %}

  {% include 'alertas/alertas.html' %}

  <script>
    const socket = io();

    socket.on('message', msg => {
      Toast.fire({
        icon: "success",
        title: msg,
      });
    });
  </script>

  <script>
    function mandarMensaje(mensaje) {
      socket.emit('message', mensaje);
    }
  </script>
</body>

</html>

src/templates/login.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>CooKing - Inicio sesión</title>
    <link
      rel="stylesheet"
      href="../static/libs/bootstrap5/css/bootstrap.min.css"
    />
    <link rel="icon" type="image/png" href="../static/img/cookie_1.png" />
    <link rel="stylesheet" href="../static/css/layout.css" />
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans"
      rel="stylesheet"
    />

    <link
      href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      rel="stylesheet"
      integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="../static/css/layout.css" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
    />
    <link rel="stylesheet" href="../static/css/login.css" />
    <script src="https://unpkg.com/scrollreveal@4.0.5/dist/scrollreveal.min.js"></script>
    <link rel="stylesheet" href="../static/css/login.css" />
  </head>

  <body>
    <section class="min-vh-100">
      <div class="container">
        <div class="hero-bg">
          <div class="particles-container">
            <canvas id="hero-particles"></canvas>
          </div>
        </div>
        <div class="box-form">
          <div class="left">
            <div class="overlay text-center">
              <a href="{{ url_for('main.index') }}"
                ><img src="../static/img/logo.png" class="logo" alt="Logo"
              /></a>

              <h1>Bienvenido a COOKING</h1>
              <p>Inicia sesión para empezar a crear tus recetas favoritas</p>
            </div>
          </div>

          <div class="right">
            <h5>Iniciar Sesión</h5>
            <br />
            {% with messages = get_flashed_messages() %} {% if messages %}
            <div class="notification is-danger">{{ messages[0] }}</div>
            {% endif %} {% endwith %}
            <form method="POST" action="/login">
              <input type="hidden" name="csrf_token" value="{{csrf_token()}}" />
              <div class="inputs">
                <div class="mb-3">
                  <input
                    class="input is-large"
                    type="text"
                    class="form-control"
                    id="usuario"
                    name="usuario"
                    aria-describedby="Usuario"
                    placeholder="Nombre de usuario"
                  />
                </div>
                <div class="mb-3">
                  <input
                    class="input is-large"
                    type="password"
                    class="form-control"
                    name="contrasenia"
                    id="contrasenia"
                    placeholder="Contraseña"
                  />
                </div>
              </div>
              <div class="mb-3 form-check">
                <input
                  type="checkbox"
                  class="form-check-input"
                  id="recordarme"
                />
                <label class="form-check-label" for="recordarme"
                  >Recordarme</label
                >
              </div>
              <br />
              <div class="button-control">
                <div class="button-outline">
                  <input
                    class="button"
                    type="submit"
                    value="Ingresar"
                    id="login"
                  />
                </div>
              </div>
            </form>
          </div>
        </div>

        <script src="../static/js/404.js"></script>
      </div>
    </section>
  </body>
</html>