src/routes/cocina.py
from datetime import datetime, timedelta
from importlib.metadata import requires

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_required

from database.models import (
    Compra,
    Insumo,
    InsumosReceta,
    LoteInsumo,
    Proveedor,
    Receta,
    SolicitudProduccion,
    Usuario,
    db,
)
from forms import forms
from logger import logger as log
from routes.auth import requires_role

cocina = Blueprint("cocina", __name__, url_prefix="/cocina")


@cocina.route("/cocinar")
@requires_role("cocinero")
def cocinar():
    solicitudesProduccion = SolicitudProduccion.query.filter(SolicitudProduccion.estatus != 4).all()

    return render_template(
        "modulos/cocina/cocinar.html",
        solicitudesProduccion=solicitudesProduccion,
        current_datetime=datetime.now(),
    )


@cocina.route("/recetas")
@login_required
def recetas():
    return redirect(url_for("cocina."))


@cocina.route("/aceptar-solicitud/<int:idSolicitud>")
@login_required
def aceptarSolicitud(idSolicitud):
    solicitudProduccion = SolicitudProduccion.query.get_or_404(idSolicitud)

    if solicitudProduccion:
        solicitudProduccion.estatus = 2

        insumosReceta = InsumosReceta.query.filter_by(
            idReceta=solicitudProduccion.idReceta
        ).all()

        receta = Receta.query.get_or_404(solicitudProduccion.idReceta)

        mensajeReceta = f"Descripción receta: \n{receta.descripcion}\n\n"
        mensajeReceta += "Los ingredientes para esta receta son:\n"

        for insumoReceta in insumosReceta:
            insumo = Insumo.query.get_or_404(insumoReceta.idInsumo)
            
            cantidadNecesaria = insumoReceta.cantidad * solicitudProduccion.tandas
            
            if insumo.unidad_medida == "Kilos":
                if cantidadNecesaria >= 1:
                    unidadMedida = "kg"
                    cantidadFormateada = cantidadNecesaria
                else:
                    unidadMedida = "g"
                    cantidadFormateada = cantidadNecesaria * 1000

            elif insumo.unidad_medida == "Litros":
                if cantidadNecesaria >= 1:
                    unidadMedida = "l"
                    cantidadFormateada = cantidadNecesaria
                else:
                    unidadMedida = "ml"
                    cantidadFormateada = cantidadNecesaria * 1000
            
            mensajeReceta += f"{insumo.nombre}: {cantidadFormateada:.2f} {unidadMedida}\n"

        db.session.commit()

        flash(mensajeReceta, "receta")

        return redirect(url_for("cocina.cocinar"))
    else:
        flash(
            "No se encontro la solicitud de producción con los datos proporcionados",
            "info",
        )
        return redirect(url_for("cocina.cocinar"))


@cocina.route("/finalizar-solicitud/<int:idSolicitud>", methods=["POST"])
@login_required
def finalizarSolicitud(idSolicitud):
    solicitudProduccion = SolicitudProduccion.query.get_or_404(idSolicitud)

    if solicitudProduccion.estatus == 2:
        print("MERMA GALLETA")
        print(request.form.get("mermaGalleta"))

        solicitudProduccion.merma = request.form.get("mermaGalleta")
        solicitudProduccion.estatus = 3

        db.session.commit()

        flash("Solicitud finalizada correctamente", "success")
        return redirect(url_for("cocina.cocinar"))
    else:
        flash(
            "La solicitud se encuentra en un status diferente a solicitud en preparación, no se puede finalizar",
            "error",
        )
        return redirect(url_for("cocina.cocinar"))


@cocina.route("/rechazar-solicitud/<int:idSolicitud>", methods=["POST"])
@login_required
def rechazarSolicitud(idSolicitud):
    solicitudProduccion = SolicitudProduccion.query.get_or_404(idSolicitud)

    if solicitudProduccion.estatus == 1:
        solicitudProduccion.mensaje = request.form.get("mensaje")
        solicitudProduccion.estatus = 5

        db.session.commit()

        flash("Solicitud rechazada correctamente", "success")
        return redirect(url_for("cocina.cocinar"))
    else:
        flash(
            "La solicitud se encuentra en un status diferente a solicitud realizada, no se puede rechazar",
            "error",
        )
        return redirect(url_for("cocina.cocinar"))


@cocina.route("/posponer-solicitud/<int:idSolicitud>", methods=["POST"])
@login_required
def posponerSolicitud(idSolicitud):
    solicitudProduccion = SolicitudProduccion.query.get_or_404(idSolicitud)

    if solicitudProduccion.estatus == 1:
        solicitudProduccion.mensaje = request.form.get("mensaje")
        solicitudProduccion.estatus = 6

        db.session.commit()

        flash("Solicitud pospuesta correctamente", "success")
        return redirect(url_for("cocina.cocinar"))
    else:
        flash(
            "La solicitud se encuentra en un status diferente a solicitud realizada, no se puede posponer",
            "error",
        )
        return redirect(url_for("cocina.cocinar"))


@cocina.route("/lotes/insumos", methods=["GET", "POST"])
def lotes_insumos():
    form = forms.BusquedaLoteInsumoForm(request.form)

    form.insumo.choices = [(0, "Todas los insumos")] + [
        (insumo.id, insumo.nombre) for insumo in Insumo.query.all()
    ]

    if request.method == "POST":
        fecha_inicio_default = datetime.now().date()
        fecha_fin_default = datetime.now().date() + timedelta(
            days=365 * 1000
        )  # Ajusta el valor según sea necesario
        insumo_default = 0

        # Validación y asignación de valores
        try:
            fecha_inicio = (
                form.fecha_inicio.data
                if form.fecha_inicio.data
                else fecha_inicio_default
            )

        except ValueError:
            fecha_inicio = fecha_inicio_default

        try:
            fecha_fin = (
                form.fecha_fin.data if form.fecha_fin.data else fecha_fin_default
            )
        except ValueError:
            fecha_fin = fecha_fin_default

        insumo = form.insumo.data if form.insumo.data else insumo_default
        lotes = []

        if insumo == "0":
            lotes = (
                db.session.query(LoteInsumo, Insumo, Usuario.nombre)
                .join(Insumo, LoteInsumo.idInsumo == Insumo.id)
                .join(Compra, LoteInsumo.idCompra == Compra.id)
                .join(Usuario, Compra.idUsuario == Usuario.id)
                .join(Proveedor, Compra.id == Proveedor.id)
                .filter(
                    LoteInsumo.cantidad > 0,
                    LoteInsumo.fecha_caducidad >= fecha_inicio,
                    LoteInsumo.fecha_caducidad <= fecha_fin,
                )
                .order_by(LoteInsumo.fecha_caducidad.asc())
                .all()
            )
        else:
            lotes = (
                db.session.query(LoteInsumo, Insumo, Usuario.nombre)
                .join(Insumo, LoteInsumo.idInsumo == Insumo.id)
                .join(Compra, LoteInsumo.idCompra == Compra.id)
                .join(Usuario, Compra.idUsuario == Usuario.id)
                .join(Proveedor, Compra.id == Proveedor.id)
                .filter(
                    LoteInsumo.cantidad > 0,
                    LoteInsumo.fecha_caducidad >= fecha_inicio,
                    LoteInsumo.fecha_caducidad <= fecha_fin,
                    LoteInsumo.idInsumo == insumo,
                )
                .order_by(LoteInsumo.fecha_caducidad.asc())
                .all()
            )

        return render_template(
            "modulos/cocina/insumos.html", form=form, lotes=lotes, lista=True
        )

    lotes = (
        db.session.query(LoteInsumo, Insumo, Usuario.nombre, Proveedor.empresa)
        .join(Insumo, LoteInsumo.idInsumo == Insumo.id)
        .join(Compra, LoteInsumo.idCompra == Compra.id)
        .join(Usuario, Compra.idUsuario == Usuario.id)
        .join(Proveedor, Compra.id == Proveedor.id)
        .filter(
            LoteInsumo.cantidad > 0,
            LoteInsumo.fecha_caducidad >= datetime.now(),
        )
        .order_by(LoteInsumo.fecha_caducidad.asc())
        .all()
    )

    log.info(lotes)
    return render_template(
        "modulos/cocina/insumos.html", form=form, lotes=lotes, lista=True
    )


@cocina.route("/insumos", methods=["GET"])
@requires_role("cocinero")
def lotes_insumos_agrupados():

    insumos = Insumo.query.all()

    for insumo in insumos:
        lotes = (
            LoteInsumo.query.filter(
                LoteInsumo.idInsumo == insumo.id,
                LoteInsumo.fecha_caducidad >= datetime.now().date(),
                LoteInsumo.cantidad > 0,
            )
            .order_by(LoteInsumo.fecha_caducidad)
            .all()
        )
        insumo.num_lotes = len(lotes)
        insumo.proxima_caducidad = lotes[0].fecha_caducidad if lotes else "No hay lotes"
        insumo.cantidad = sum(lote.cantidad for lote in lotes)
        insumo.coste_promedio = (
            sum(lote.precio_unidad * lote.cantidad for lote in lotes) /
            insumo.cantidad
            if insumo.cantidad
            else 1
        )
        # agregar flash para los insumos que estan por agotarse
        if insumo.cantidad < insumo.cantidad_minima:
            flash(
                f"(Escacez) El insumo {insumo.nombre} esta por agotarse", "warning")
        # agregar flash para los insumos que sobrepasan la capacidad de almacenamiento
        if insumo.cantidad > insumo.cantidad_maxima:
            flash(
                f"(Exceso) El insumo {insumo.nombre} sobrepasa la capacidad de almacenamiento",
                "info",
            )
        # agregar flash par los lotes del insumo que estan por caducar en los proximos 3 dias
        for lote in lotes:
            if lote.fecha_caducidad <= datetime.now().date() + timedelta(days=3):
                flash(

src/templates/modulos/cocina/cocinar.html
{% extends 'inicio.html' %}

{% block title %}Solicitudes Producción{% endblock%}

{% block styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/cocina.scss.css') }}" />
{% endblock %}

{% block content %}
<h1 class="titulo-cocina">Solicitudes producción</h1>
<div class="contenedor-solicitudes" id="contenedor">
  {% for solicitudProduccion in solicitudesProduccion %}
  <div class="order-card">
    <h2 class="title">{{ solicitudProduccion.receta.nombre }}</h2>
    <div class="centrar-contenido">
      <img src="{{ url_for('static', filename='img/cookies/' ~ solicitudProduccion.receta.imagen) }}" />
    </div>
    <div class="c-body">
      <div class="top">
        <ul class="progress-line">
          {% if solicitudProduccion.estatus >= 1 and solicitudProduccion.estatus != 5 and solicitudProduccion.estatus !=
          6%}
          <li class="green">
            {% elif solicitudProduccion.estatus == 5 or solicitudProduccion.estatus == 6 %}
          <li class="red">
            {% else %}
          </li>

          <li>
            {% endif %}
            {% if solicitudProduccion.estatus >= 1 and solicitudProduccion.estatus != 5 and solicitudProduccion.estatus
            != 6%}
            <span>Solicitud realizada</span>
            <div class="icon">
              <i class="fa-solid fa-check"></i>
              {% elif solicitudProduccion.estatus == 5 %}
              <span>Solicitud rechazada</span>
              <div class="icon">
                <i class="fa-solid fa-xmark"></i>
                {% elif solicitudProduccion.estatus == 6 %}
                <span>Solicitud pospuesta</span>
                <div class="icon">
                  <i class="fa-solid fa-xmark"></i>
                  {% endif %}
                </div>
          </li>

          {% if solicitudProduccion.estatus >= 2 and solicitudProduccion.estatus != 5 and solicitudProduccion.estatus !=
          6%}
          <li class="green">
            {% else %}
          </li>

          <li>
            {% endif %}
            <span>En preparación</span>
            <div class="icon">
              <i class="fa-solid fa-fire-burner"></i>
            </div>
          </li>

          {% if solicitudProduccion.estatus >= 3 and solicitudProduccion.estatus != 5 and solicitudProduccion.estatus !=
          6%}
          <li class="green">{% else %}</li>

          <li>
            {% endif %}
            <span>Listo para entrega</span>
            <div class="icon">
              <i class="fa-solid fa-share"></i>
            </div>
          </li>

          {% if solicitudProduccion.estatus >= 4 and solicitudProduccion.estatus != 5 and solicitudProduccion.estatus
          !=6%}
          <li class="green">{% else %}</li>

          <li>
            {% endif %}
            <span>Producción entregada</span>
            <div class="icon">
              <i class="fa-solid fa-circle-check"></i>
            </div>
          </li>
        </ul>

        <div class="contenedor-usuarios-detalles">
          <div class="c-media b-border contenedor-detalles">
            <div class="icono">
              <i class="fa-solid fa-circle-user"></i>
            </div>
            <div class="details">
              <div class="titulo-detalle">Solicitud</div>
              <div class="contenido-detalle">
                {{ solicitudProduccion.usuarioSolicitud.nombre }}
              </div>
            </div>
          </div>

          <div class="c-media b-border contenedor-detalles">
            <div class="icono">
              <i class="fa-solid fa-kitchen-set"></i>
            </div>
            <div class="details">
              <div class="titulo-detalle">Cocinero</div>
              <div class="contenido-detalle">
                {% if solicitudProduccion.usuarioProduccion is not none %}
                {{ solicitudProduccion.usuarioProduccion.nombre }}
                {% else %} No asignado {% endif %}
              </div>
            </div>
          </div>

          <div class="c-media b-border contenedor-detalles">
            <div class="icono">
              <i class="fa-solid fa-calendar-days"></i>
            </div>
            <div class="details">
              <div class="titulo-detalle">Fecha</div>
              <div class="contenido-detalle">
                {{ solicitudProduccion.fecha_solicitud.strftime('%d de %B del %Y') }}
              </div>
            </div>
          </div>

          <div class="c-media b-border contenedor-detalles">
            <div class="icono">
              <i class="fa-regular fa-clock"></i>
            </div>
            <div class="details">
              <div class="titulo-detalle">Hora</div>
              <div class="contenido-detalle">
                {{ solicitudProduccion.fecha_solicitud.strftime('%H:%M:%S') }}
              </div>
            </div>
          </div>

          <div class="c-media b-border contenedor-detalles">
            <div class="icono">
              <i class="fa-solid fa-hashtag"></i>
            </div>
            <div class="details">
              <div class="titulo-detalle">Tandas</div>
              <div class="contenido-detalle">
                {{ solicitudProduccion.tandas }}
              </div>
            </div>
          </div>

          {% if solicitudProduccion.estatus == 5 %}
          <div class="c-media b-border contenedor-detalles">
            <div class="icono">
              <i class="fa-regular fa-comment"></i>
            </div>
            <div class="details">
              <div class="titulo-detalle">Mensaje rechazo</div>
              <div class="contenido-detalle">
                {{ solicitudProduccion.mensaje }}
              </div>
            </div>
          </div>
          {% endif %}

          {% if solicitudProduccion.estatus == 6 %}
          <div class="c-media b-border contenedor-detalles">
            <div class="icono">
              <i class="fa-regular fa-comment"></i>
            </div>
            <div class="details">
              <div class="titulo-detalle">Mensaje pospuesto</div>
              <div class="contenido-detalle">
                {{ solicitudProduccion.mensaje }}
              </div>
            </div>
          </div>
          {% endif %}
        </div>
      </div>
    </div>

    <div class="botones-solicitud">
      {% if solicitudProduccion.estatus == 1 or solicitudProduccion.estatus == 6%}
      <form action="{{ url_for('cocina.aceptarSolicitud', idSolicitud = solicitudProduccion.id) }}"
        id="formAceptarSolicitud{{solicitudProduccion.id}}">
        <button type="button" class="boton btn-aceptar" onclick="aceptarSolicitud('{{ solicitudProduccion.id }}')">
          Aceptar
        </button>
      </form>
      {% endif %}

      {% if solicitudProduccion.estatus == 2 %}
      <form action="{{ url_for('cocina.finalizarSolicitud', idSolicitud = solicitudProduccion.id) }}"
        id="formFinalizarSolicitud{{solicitudProduccion.id}}" method="POST">
        <input type="hidden" name="csrf_token" value="{{csrf_token()}}" />
        <input type="hidden" name="mermaGalleta" id="mermaGalleta{{solicitudProduccion.id}}" />
        <button type="button" class="boton btn-aceptar"
          onclick="finalizarSolicitud('{{ solicitudProduccion.id }}', '{{ solicitudProduccion.tandas * solicitudProduccion.receta.piezas}}')">
          Finalizar producción
        </button>
      </form>
      {% endif %}

      {% if (solicitudProduccion.estatus == 2 and (current_datetime -
      solicitudProduccion.fecha_solicitud).total_seconds() / 60 <= 10) %} <form
        action="{{ url_for('cocina.rechazarSolicitud', idSolicitud = solicitudProduccion.id) }}"
        id="formRechazarSolicitud{{solicitudProduccion.id}}">
        <button type="button" class="boton btn-cancelar" onclick="rechazarSolicitud('{{ solicitudProduccion.id }}')">
          Regresar status
        </button>
        </form>
        {% endif %}


        {% if solicitudProduccion.estatus == 1 %}
        <form action="{{ url_for('cocina.posponerSolicitud', idSolicitud = solicitudProduccion.id) }}"
          id="formPosponerSolicitud{{solicitudProduccion.id}}" method="POST">
          <input type="hidden" name="csrf_token" value="{{csrf_token()}}" />
          <input type="hidden" name="mensaje" id="mensajePosponer{{solicitudProduccion.id}}" />
          <button type="button" class="boton btn-posponer" onclick="posponerSolicitud('{{ solicitudProduccion.id }}')">
            Posponer
          </button>
        </form>
        {% endif %}

        {% if solicitudProduccion.estatus == 1 %}
        <form action="{{ url_for('cocina.rechazarSolicitud', idSolicitud = solicitudProduccion.id) }}"
          id="formRechazarSolicitud{{solicitudProduccion.id}}" method="POST">
          <input type="hidden" name="csrf_token" value="{{csrf_token()}}" />
          <input type="hidden" name="mensaje" id="mensajeRechazo{{solicitudProduccion.id}}" />
          <button type="button" class="boton btn-cancelar" onclick="rechazarSolicitud('{{ solicitudProduccion.id }}')">
            Rechazar
          </button>
        </form>
        {% endif %}

    </div>
  </div>
  {% else %}
  <div class="solicitudes-vacias">
    <h2>No se encontraron solicitudes de producción.</h2>
  </div>
  {% endfor %}
</div>

<script>
  $(document).ready(function () {
    $("#contenedor").sortable({
      start: function (event, div) {
        div.item.data("start-index", div.item.index());
      },
      update: function (event, div) {
        var startIndex = div.item.data("start-index");
        var endIndex = div.item.index();
        console.log(
          "El elemento se movió de la posición " +
          (startIndex + 1) +
          " a la posición " +
          (endIndex + 1)
        );
      },
    });
    $("#contenedor").disableSelection();
  });
</script>

<script>
  function aceptarSolicitud(id) {
    Swal.fire({
      title: "¿Estás seguro de aceptar la solicitud?",
      showCancelButton: true,
      confirmButtonText: "Sí",
      cancelButtonText: "Cancelar",
      icon: "question",
    }).then((result) => {
      let formAceptarSolicitud = document.getElementById(
        "formAceptarSolicitud" + id
      );
      formAceptarSolicitud.submit();
    });
  }

  function finalizarSolicitud(id, cantidadMaxima) {
    Swal.fire({
      title: "¿Estás seguro de finalizar la producción?",
      showCancelButton: true,
      confirmButtonText: "Sí",
      cancelButtonText: "Cancelar",
      icon: "question",
    }).then((result) => {
      if (result.isConfirmed) {
        Swal.fire({
          title: 'Merma en producción',
          text: '¿Tuviste merma en esta producción? Coloca las piezas de merma.',
          input: 'number', // Permite al usuario introducir un número
          inputPlaceholder: 'Número de piezas de merma',
          inputValidator: (value) => {
            // Validación opcional, puedes personalizar el mensaje de error
            if (!value) {
              return 'Debes ingresar un número de piezas de merma';
            }

            if (parseInt(value) > parseInt(cantidadMaxima)) {
              return 'La merma no puede ser mayor que las piezas producidas ' + cantidadMaxima;
            }

            if (parseInt(value) < 0) {
              return 'La merma no puede ser menor que 0 piezas';
            }
          },
          showCancelButton: true,
          confirmButtonText: 'Aceptar',
          cancelButtonText: 'Cancelar'
        }).then((mermaResult) => {
          if (mermaResult.isConfirmed) {
            document.getElementById('mermaGalleta' + id).value = mermaResult.value

            let formFinalizarSolicitud = document.getElementById("formFinalizarSolicitud" + id);

            formFinalizarSolicitud.submit();
          }
        });
      }
    });
  }


  function posponerSolicitud(id) {
    Swal.fire({
      title: "¿Estás seguro de posponer la solicitud?",
      showCancelButton: true,
      confirmButtonText: "Sí",
      cancelButtonText: "Cancelar",
      icon: "question",
    }).then((result) => {
      if (result.isConfirmed) {
        Swal.fire({
          title: 'Motivo para posponer',
          input: 'textarea',
          inputLabel: 'Por favor, proporciona el motivo para posponer:',
          inputPlaceholder: 'Escribe aquí...',
          showCancelButton: true,
          confirmButtonText: 'Enviar',
          cancelButtonText: 'Cancelar',
          showLoaderOnConfirm: true,
          preConfirm: (motivo) => {
            document.getElementById('mensajePosponer' + id).value = motivo;

            let formRechazarSolicitud = document.getElementById("formPosponerSolicitud" + id);
            formRechazarSolicitud.submit();
          },
          allowOutsideClick: () => !Swal.isLoading()
        });
      }
    });
  }

  function rechazarSolicitud(id) {
    Swal.fire({
      title: "¿Estás seguro de rechazar la solicitud?",
      showCancelButton: true,
      confirmButtonText: "Sí",
      cancelButtonText: "Cancelar",
      icon: "question",
    }).then((result) => {
      if (result.isConfirmed) {
        Swal.fire({
          title: 'Motivo de rechazo',
          input: 'textarea',
          inputLabel: 'Por favor, proporciona el motivo de rechazo:',
          inputPlaceholder: 'Escribe aquí...',
          showCancelButton: true,
          confirmButtonText: 'Enviar',
          cancelButtonText: 'Cancelar',
          showLoaderOnConfirm: true,
          preConfirm: (motivo) => {
            document.getElementById('mensajeRechazo' + id).value = motivo;

            let formRechazarSolicitud = document.getElementById("formRechazarSolicitud" + id);
            formRechazarSolicitud.submit();
          },
          allowOutsideClick: () => !Swal.isLoading()
        });
      }
    });
  }


</script>
{% endblock %}

src/templates/modulos/cocina/insumo_individual.html
{% extends 'inicio.html' %} {% block title %}Almacen{% endblock %} {% block
styles %} {% endblock %} {%from "_macros.html" import render_field%} {% block
content %}
<div style="width: 100%; text-align: center">
  <h1>Insumos</h1>
</div>
<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button
        class="accordion-button collapsed"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#collapseOne"
        aria-expanded="false"
        aria-controls="collapseOne"
      >
        {% with messages = get_flashed_messages() %} {% if messages %}
        <div style="color: #e6b252">{{ messages|length }}</div>
        {% endif %} {% endwith %} &nbsp; Advertencias sobre los lotes de insumos
      </button>
    </h2>
    <div
      id="collapseOne"
      class="accordion-collapse collapse"
      aria-labelledby="headingOne"
      data-bs-parent="#accordionExample"
    >
      <div class="accordion-body">
        {% with messages = get_flashed_messages(with_categories=true) %} {% if
        messages %} {% for category, message in messages %}
        <div class="alert alert-{{ category }}" style="width: 90%">
          {{ message }}
        </div>
        {% endfor %} {% endif %} {% endwith %}
      </div>
    </div>
  </div>
</div>
<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a
      href="{{url_for('cocina.lotes_insumos_agrupados')}}"
      style="text-decoration: none"
    >
      <button
        class="nav-link active"
        id="nav-lote1-tab"
        data-bs-toggle="tab"
        data-bs-target="#nav-lote1"
        type="button"
        role="tab"
        aria-controls="nav-lote1"
        aria-selected="true"
      >
        Insumos
      </button>
    </a>
    <a href="{{url_for('cocina.lotes_insumos')}}" style="text-decoration: none">
      <button
        class="nav-link"
        id="nav-lote1-tab"
        data-bs-toggle="tab"
        data-bs-target="#nav-lote1"
        type="button"
        role="tab"
        aria-controls="nav-lote1"
        aria-selected="false"
      >
        Lotes Insumos
      </button>
    </a>
  </div>
</nav>

<div class="container">
  <table class="table table-striped table-bordered mt-5">
    <thead>
      <tr>
        <th scope="col">Insumo</th>
        <th scope="col">Lotes Vigentes</th>
        <th scope="col">Fecha de Caducidad más próxima</th>
        <th scope="col">Cantidad Disponible</th>
        <th scope="col">Coste unitario promedio</th>
        <th scope="col">Almacenaje Recomendado</th>
      </tr>
    </thead>
    <tbody>
      {% for insumo in insumos %}
      <tr>
        <td>{{ insumo.nombre }}</td>
        <td>{{ insumo.num_lotes }}</td>
        <td>{{ insumo.proxima_caducidad }}</td>
        <td>{{ insumo.cantidad }} {{insumo.unidad_medida}}</td>
        <td>$ {{ insumo.coste_promedio | round(2)}}</td>
        <td>
          {{ insumo.cantidad_maxima }} - {{ insumo.cantidad_minima }} {{
          insumo.unidad_medida }}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

src/templates/modulos/cocina/lotes_insumos.html
{% extends 'inicio.html' %} {% block title %}Almacen{% endblock %} {% block
styles %} {% endblock %} {% block content %}
<div style="width: 100%; text-align: center">
  <h1>Almacén</h1>
</div>
{% with messages = get_flashed_messages() %} {% if messages %} {% for message in
messages %}
<div class="alert alert-success" style="width: 90%">{{ message }}</div>
{% endfor %} {% endif %} {% endwith %} {% if admin or vendedor %}
<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a href="{{url_for('main.galletas')}}">
      <button
        class="nav-link active"
        id="nav-lote1-tab"
        data-bs-toggle="tab"
        data-bs-target="#nav-lote1"
        type="button"
        role="tab"
        aria-controls="nav-lote1"
        aria-selected="true"
      >
        Lotes de Galletas
      </button>
    </a>
    <a href="{{url_for('main.galletas')}}">
      <button
        class="nav-link"
        id="nav-lote2-tab"
        data-bs-toggle="tab"
        data-bs-target="#nav-lote2"
        type="button"
        role="tab"
        aria-controls="nav-profile"
        aria-selected="false"
      >
        Lotes de Insumos
      </button>
    </a>
  </div>
</nav>
{% endif %} {% endblock %}

src/templates/modulos/cocina/recetas.html
{% extends 'inicio.html' %}

{% block title %}Solicitudes Producción{% endblock %}

{% block styles %}

{% endblock %}

{% block content %}

{% endblock %}