src/forms/utilidad.py
""" FORMULARIOS DE UTILIDADES """

from gc import disable
from math import cos

from click import style
from sqlalchemy import Integer
from wtforms import FloatField, Form, IntegerField, SelectField, SubmitField, validators

from database.models import Receta


class GetRecetaForm(Form):
    """CLASE QUE DEFINE EL FORMULARIO DE LA UTILIDAD DE LAS RECETAS"""

    receta = SelectField(
        "Receta",
        [
            validators.DataRequired(message="El Campo es Requerido"),
        ],
        choices=[],
    )
    submit = SubmitField("GUARDAR")

    def __str__(self):
        """Devuelve una representación en cadena de texto de los datos del formulario."""
        # Inicializa una cadena de texto vacía para almacenar la representación
        form_representation = ""

        # Recorre cada campo del formulario
        for field_name, field in self._fields.items():
            # Añade el nombre del campo y su valor al string
            form_representation += f"{field_name}: {field.data}, "

            # Añade los mensajes de error o validación si existen
            if field.errors:
                form_representation += f"Errores: {', '.join(field.errors)}, "

        # Elimina la última coma y espacio
        form_representation = form_representation.rstrip(", ")

        return form_representation

    def __init__(self, *args, **kwargs):
        super(GetRecetaForm, self).__init__(*args, **kwargs)
        # Consultar la base de datos para obtener las recetas
        self.receta.choices = [
            (receta.id, receta.nombre) for receta in Receta.query.all()
        ]


class UtilidadForm(Form):
    """Formulario para calcular la utilidad de una receta"""

    id_receta = IntegerField(
        "ID Receta",
        render_kw={"style": "display: none"},
        validators=[
            validators.DataRequired(message="El Campo es Requerido"),
            validators.NumberRange(min=1, message="Ingresa un ID Válido"),
        ],
    )
    costo_unitario = FloatField(
        "Costo Unitario",
        render_kw={"disabled": ""},
    )
    cantidad_galletas = IntegerField(
        "Cantidad de Galletas",
        render_kw={"disabled": ""},
    )
    costo_total = FloatField("Costo Total", render_kw={"disabled": ""})
    costo_venta = FloatField(
        "Costo de Venta",
        [
            validators.DataRequired(message="El Campo es Requerido"),
            validators.NumberRange(min=1, message="Ingresa un Costo Válido"),
        ],
    )
    submit = SubmitField("CALCULAR")

src/routes/utilidad.py
""" Rutas de la sección de utilidad """

from datetime import datetime

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_required
from sqlalchemy import func

from database.models import Insumo, InsumosReceta, LoteInsumo, Receta, db
from forms import utilidad as utilidad_form
from logger import logger as log
from routes.auth import requires_role

utilidad = Blueprint("utilidad", __name__, url_prefix="/utilidad")


@utilidad.route("/")
@requires_role("admin")
def gestion():
    """Ruta para la página de inicio de la sección de utilidad"""
    form = utilidad_form.GetRecetaForm(request.form)
    form_utilidad = utilidad_form.UtilidadForm(request.form)

    return render_template(
        "utilidad/utilidad.html", form=form, formUtilidad=form_utilidad
    )


@utilidad.route("/obtener-ingredientes", methods=["POST"])
@requires_role("admin")
def obtener_ingredientes():
    """Ruta para obtener los ingredientes de una receta"""
    form = utilidad_form.GetRecetaForm(request.form)
    form_utilidad = utilidad_form.UtilidadForm(request.form)

    id_receta = form.receta.data

    ingredientes_receta = (
        db.session.query(
            InsumosReceta, Insumo.nombre, Insumo.unidad_medida
        )  # Añadir Insumo.nombre aquí
        .join(Insumo, InsumosReceta.idInsumo == Insumo.id)  # Unir las tablas
        .filter(InsumosReceta.idReceta == id_receta)
        .all()
    )

    ingredientes_con_nombres = []

    for insumo_receta, nombre_insumo, unidad_medida in ingredientes_receta:
        ingredientes_con_nombres.append(
            {
                "insumo": nombre_insumo,
                "inventario": calcular_precio_total(insumo_receta.idInsumo)[
                    "cantidad_total"
                ],
                "unidad": unidad_medida,
                "precio_total": round(
                    calcular_precio_total(insumo_receta.idInsumo)["precio_total"], 2
                ),
                "cantidad": insumo_receta.cantidad,
                "costo_total": round(
                    insumo_receta.cantidad
                    * calcular_precio_total(insumo_receta.idInsumo)["precio_total"],
                    2,
                ),
            }
        )

    receta_seleccionada = Receta.query.get(id_receta)
    titulo_receta = receta_seleccionada.nombre if receta_seleccionada else None
    utilidad_receta = receta_seleccionada.utilidad if receta_seleccionada else None
    cantidad_galletas = receta_seleccionada.piezas if receta_seleccionada else None

    form_utilidad.id_receta.data = id_receta
    form_utilidad.costo_total.data = round(
        sum(ingrediente["costo_total"] for ingrediente in ingredientes_con_nombres), 2
    )
    form_utilidad.costo_venta.data = utilidad_receta
    form_utilidad.costo_unitario.data = round(
        form_utilidad.costo_total.data / cantidad_galletas, 2
    )
    form_utilidad.cantidad_galletas.data = cantidad_galletas

    return render_template(
        "utilidad/utilidad.html",
        form=form,
        formUtilidad=form_utilidad,
        ingredientes=ingredientes_con_nombres,
        titulo_receta=titulo_receta,
        receta_seleccionada=id_receta,
    )


@utilidad.route("/guardar", methods=["POST"])
@requires_role("admin")
def guardar():
    """Ruta para guardar la utilidad de una receta"""
    form_utilidad = utilidad_form.UtilidadForm(request.form)

    id_receta = form_utilidad.id_receta.data
    precio = form_utilidad.costo_venta.data

    receta_seleccionada = Receta.query.get(id_receta)
    receta_seleccionada.utilidad = precio
    db.session.commit()

    flash(
        "Utilidad Registrada Correctamente",
        "success",
    )

    return redirect(url_for("utilidad.gestion"))


def calcular_precio_total(id_insumo):
    """
    Calcula el precio total de la harina basado en la cantidad total disponible,
    considerando solo los lotes con fecha de caducidad mayor a la fecha actual.

    Parámetros:
    - id_insumo: El ID del insumo (harina) para el cual se calculará el precio total.

    Retorna:
    - Un diccionario con el precio total calculado y la cantidad total de harina disponible.
    """

    fecha_actual = datetime.now().date()

    # Realiza la consulta a la base de datos para obtener los lotes de harina por id_insumo
    # y que tengan una fecha de caducidad mayor a la fecha actual
    lotes = (
        db.session.query(LoteInsumo)
        .filter(
            LoteInsumo.idInsumo == id_insumo, LoteInsumo.fecha_caducidad > fecha_actual
        )
        .all()
    )

    # Inicializa el total de cantidad y el total de precio
    total_cantidad = 0
    total_precio = 0

    # Itera sobre cada lote
    for lote in lotes:
        # Suma la cantidad y el precio de cada lote al total
        total_cantidad += lote.cantidad
        total_precio += lote.cantidad * lote.precio_unidad

    # Calcula el precio total
    precio_total = total_precio / total_cantidad if total_cantidad > 0 else 0

    # Retorna el precio total y la cantidad total
    return {"precio_total": precio_total, "cantidad_total": total_cantidad}

src/templates/utilidad/utilidad.html
{% import '_macros.html' as macro %} 

{% extends "inicio.html" %} 

{% block title %} UTILIDADES {% endblock %} 

{% block content %}
<div>
    <div class="text-center h1">
        <h1>UTILIDADES</h1>
    </div>
    <div class="row text-center">
        <div class="col-12">
            <form id="ingredientesForm" action="{{ url_for('utilidad.obtener_ingredientes')}}" method="POST">
                <input type="hidden" name="csrf_token" value="{{csrf_token()}}" />
                {% set valor_seleccionado = receta_seleccionada if receta_seleccionada else '' %}

                {{ macro.select(form.receta, valor_seleccionado) }}                        
                <!-- {{ macro.submit_button(form.submit) }} -->

            </form>
            
        </div>
        
    </div>
    <div class="col-12 text-center my-3">
        <h1>{{ titulo_receta }}</h1>
    </div>
    <div class="row mx-5 my-5">
        <div class="card p-0">
            <div class="table-responsive">
            <table class="table table-hover table-bordered">
                <thead >
                    <tr>
                        <th scope="col">INSUMO</th>
                        <th scope="col">INVENTARIO</th>
                        <th scope="col">PRECIO X KILO</th>
                        <th scope="col">CANTIDAD NECESARIA</th>
                        <th scope="col">COSTO TOTAL</th>
                    </tr>
                </thead>
                <tbody class="table-group-divider">

                    {% for ingrediente in ingredientes %}
                    <tr>
                        <td>{{ ingrediente.insumo }}</td>
                        <td>{{ ingrediente.inventario }} {{ ingrediente.unidad }}</td>
                        <td>$ {{ ingrediente.precio_total }}</td>
                        <td>{{ ingrediente.cantidad }} {{ ingrediente.unidad }}</td>
                        <td>$ {{ ingrediente.costo_total }}</td>
                    {% endfor %}
                    
                </tbody>
            </table>
        </div>
        </div>
        
    </div>

    <form action="{{ url_for('utilidad.guardar')}}" method="POST" class="p-0">
            <input type="hidden" name="csrf_token" value="{{csrf_token()}}" />
            <input id="{{ formUtilidad.id_receta.name }}" type="hidden" name="id_receta" {% if formUtilidad.id_receta.data %}
                value="{{ formUtilidad.id_receta.data }}"
            {% endif %}>
            <div class="row mx-5">
                <div class="col-6">                
                    {{ macro.input_float(formUtilidad.costo_unitario) }}
                </div>
                <div class="col-6">            
                    {{ macro.input_float(formUtilidad.cantidad_galletas) }}                
                </div>
            </div>
                        
            <div class="row mx-5">
                <div class="col-6">                    
                    {{ macro.input_float(formUtilidad.costo_total) }}
                </div>
                <div class="col-6">                    
                    {{ macro.input_float(formUtilidad.costo_venta) }}
                    <div id="errorContainer" class="mx-5"></div>
                </div>
            </div>
            <div class="col-12 my-2">
                <div class="text-center">
                    <button id="btnGuardarUtilidad" type="submit" class="btn btn-primary">GUARDAR</button>
                </div>
            </div>
        </form>
        
        
</div>
{% endblock %} 

{% block jscode %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
    document.querySelector('select[name="receta"]').addEventListener('change', function() {
        document.getElementById('ingredientesForm').submit();
    });
    document.querySelector('input[name="costo_total"]').disabled = true;
    document.querySelector('input[name="costo_unitario"]').disabled = true;
    document.querySelector('input[name="cantidad_galletas"]').disabled = true;
    document.querySelector('input[name="costo_venta"]').addEventListener('keypress', function(event) {
        console.log("SCRIPT PARA NO PERMITIR LETRAS")
        // Obtener el código de la tecla presionada
        let keyCode = event.keyCode || event.which;

        // Permitir solo números (0-9), el punto (.) y la tecla de retroceso (Backspace)
        if (!(keyCode >= 48 && keyCode <= 57) && // Números del 0 al 9
            !(keyCode >= 96 && keyCode <= 105) && // Números numéricos del teclado
            keyCode !== 190 && // Punto (.)
            keyCode !== 8) { // Tecla de retroceso (Backspace)
            // Cancelar el evento si la tecla no es un número o un punto
            event.preventDefault();
        }
    });
    
    
});
</script>

<script>
    document.getElementById('btnGuardarUtilidad').disabled = true;
    document.addEventListener('DOMContentLoaded', function() {

        // Obtener los elementos del DOM
        const txtPrecio = document.getElementById('costo_venta');
        const txtCosto = document.getElementById('costo_unitario');
        const errorContainer = document.getElementById('errorContainer');

        // Función para validar el precio final
        function validarPrecioFinal() {
            console.log("SCRIPT PARA VALIDAR EL PRECIO FINAL")
            const precioFinal = parseFloat(txtPrecio.value);
            const costoProduccion = parseFloat(txtCosto.value);

            // Verificar si el precio final es menor que el costo de producción
            if (precioFinal < costoProduccion || isNaN(precioFinal)) {
                // Agregar clase de error al campo de precio final
                txtPrecio.classList.add('is-invalid');
                document.getElementById('btnGuardarUtilidad').disabled = true;
                // Mostrar mensaje de error
                errorContainer.innerHTML = '<div class="invalid-feedback text-uppercase" style="display: block">El precio final no puede ser menor que el costo unitario.</div>';
            } else {
                // Remover clase de error si el precio es válido
                txtPrecio.classList.remove('is-invalid');
                errorContainer.innerHTML = '';
                document.getElementById('btnGuardarUtilidad').disabled = false;
            }
        }

        // Escuchar el evento 'input' en el campo de precio final para validar mientras el usuario escribe
        txtPrecio.addEventListener('input', validarPrecioFinal);

        txtPrecio.focus();
        validarPrecioFinal();
    });

        
</script>

{% endblock %}